# Generated by Django 3.1.2 on 2021-10-09 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_artist_genre_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.FileField(default=None, upload_to='products'),
        ),
    ]
