# Generated by Django 3.1.2 on 2021-10-09 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20211009_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='songs',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.song'),
        ),
    ]
