# Generated by Django 3.1.2 on 2021-10-09 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20211009_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='songs',
        ),
        migrations.AddField(
            model_name='song',
            name='product_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
    ]
