# Generated by Django 3.1.2 on 2021-10-09 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20211010_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.artist'),
        ),
        migrations.AlterField(
            model_name='product',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.genre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.label'),
        ),
        migrations.AlterField(
            model_name='song',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
    ]
