# Generated by Django 3.1.2 on 2021-10-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20211010_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.FileField(default=None, upload_to='products'),
        ),
    ]
