# Generated by Django 3.1.2 on 2021-10-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20211011_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='email',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='apiuser',
            name='password',
            field=models.CharField(max_length=23),
        ),
        migrations.AlterField(
            model_name='apiuser',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
