# Generated by Django 3.1.2 on 2021-12-13 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20211114_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
